{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "ms.fullname" . }}
  labels:
    {{- include "ms.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ include "ms.fullname" . }}
    creationPolicy: Owner
  data:
    {{- range .Values.externalSecret.secrets }}
    - secretKey: {{ .property }}
      remoteRef:
        key: {{ .key }}
    {{- end }}
{{- end }}
